// Code generated by goctl. DO NOT EDIT.
package types

type LoginResp struct {
	Token string `json:"token"`
	Uid   string `json:"uid"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type UserInfoReq struct {
	Uid string `path:"uid"`
}

type UserInfoResp struct {
	Uid   string `path:"uid"`
	Name  string `json:"name"`
	Email string `json:"email"`
}
