// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	UserName string `json:"userName"`
	Password string `json:"password"`
}

type UserInfoReq struct {
	ID string `path:"id"`
}

type UserDetailReq struct {
	ID   string `form:"id"`
	Name string `form:"name"`
}

type UserHeader struct {
	Authorization string `header:"Authorization"`
}
