// Code generated by goctl. DO NOT EDIT.

export interface LoginResp {
	token: string
	uid: string
}

export interface LoginReq {
	username: string
	password: string
}

export interface UserInfoReq {
}

export interface UserInfoReqParams {
	uid: string
}

export interface UserInfoResp {
	name: string
	email: string
}

export interface UserInfoRespParams {
	uid: string
}

