// Code generated by goctl. DO NOT EDIT.
package com.xhb.logic.http.packet.User.model;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import com.xhb.core.response.HttpResponseData;
import com.xhb.core.packet.HttpData;

public class LoginReq extends HttpData {

	private String username = "";
	private String password = "";

	public LoginReq() {
	}

	public LoginReq(String username, String password) {
		this.username = username;
		this.password = password;
	}

	@NotNull 
	public String getUsername() {
		return this.username;
	}

	public void setUsername(@NotNull String username) {
		this.username = username;
	}

	@NotNull 
	public String getPassword() {
		return this.password;
	}

	public void setPassword(@NotNull String password) {
		this.password = password;
	}

}
