// Code generated by goctl. DO NOT EDIT!
// Source: hello.proto

package helloclient

import (
	"context"

	"client/hello"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	HelloReply   = hello.HelloReply
	HelloRequest = hello.HelloRequest

	Hello interface {
		SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	}

	defaultHello struct {
		cli zrpc.Client
	}
)

func NewHello(cli zrpc.Client) Hello {
	return &defaultHello{
		cli: cli,
	}
}

func (m *defaultHello) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	client := hello.NewHelloClient(m.cli.Conn())
	return client.SayHello(ctx, in, opts...)
}
