// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"after/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

type Body struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data,omitempty"`
}

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: loginHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/info",
				Handler: userinfoHandler(serverCtx),
			},
		},
	)
}
