// Code generated by goctl. DO NOT EDIT!
// Source: hello.proto

package client

import (
	"context"

	"new/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	HelloReply   = pb.HelloReply
	HelloRequest = pb.HelloRequest

	HiService interface {
		SayHi(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	}

	defaultHiService struct {
		cli zrpc.Client
	}
)

func NewHiService(cli zrpc.Client) HiService {
	return &defaultHiService{
		cli: cli,
	}
}

func (m *defaultHiService) SayHi(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	client := pb.NewHiServiceClient(m.cli.Conn())
	return client.SayHi(ctx, in, opts...)
}
